name: GiantPicks
authors: ['Bryan_lzh']
main: br.giantPicks.Main
depend: [Vault,LockettePro,BrAPI,ProtocolLib]
version: 2.0

commands:
  GiantPicks:
    aliases: [gp]
    description: 主命令
    usage: |
        /<command> list   >> 查看可用的词条表
        /<command> add [词条名] [参数...] >> 为手上的物品添加词条
        /<command> reload >> 重载插件配置